# Site settings
title:          Nour El Husseini, GRA
description:    "Personal website for Nour El Husseini."
url:            https://github.com/nelhusseini.io

# Theme
theme: minima

# Author
author:
  name:         Nour El Husseini
  email:        nbh@umd.edu
  url:          https://github.com/nelhusseini.io

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink: /blog/:year/:month/:day/:title

# Links to social media
social:
  email: nbh@umd.edu
  github: https://github.com/nelhusseini
  twitter: https://twitter.com/nbelhusseini
  linkedin: https://ba.linkedin.com/in/nour-el-husseini
  
  
